version: '3.7'

services:
  identity-server:
    image: oleksandrbondarenko777/identity-server:latest
    container_name: identity-server
    ports:
      - '8080:5000'

  core-api:
    image: oleksandrbondarenko777/core-api:latest
    container_name: core-api
    ports:
      - '8081:5002'

  ui:
    image: oleksandrbondarenko777/online-shop-ui:latest
    container_name: online-shop-ui
    ports:
      - '8082:3000'