version: '3.7'

services:
  # http://localhost:15672
  # username: guest
  # password: guest
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
    
  identity-server:
    image: oleksandrbondarenko777/identity-server:latest
    container_name: identity-server
    ports:
      - '8080:5000'
    depends_on:
      - sql-server-db

  core-api:
    image: oleksandrbondarenko777/core-api:latest
    container_name: core-api
    ports:
      - '8081:5002'
    depends_on:
      - sql-server-db

  ui:
    image: oleksandrbondarenko777/online-shop-ui:latest
    container_name: online-shop-ui
    ports:
      - '8082:3000'

  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sql-server-17
    ports:
      - '2433:1433'
    environment:
      SA_PASSWORD: "Pass1234Qq"
      ACCEPT_EULA: "Y"

networks:
  rabbitmq_go_net:
    driver: bridge