name: .NET build & test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies for CoreAPI
      run: dotnet restore OnlineShopAPI/OnlineShopAPI/OnlineShopAPI.csproj
    - name: Restore dependencies for IdentityServer
      run: dotnet restore OnlineShopAPI/IdentityServer/IdentityServer.csproj
    - name: Build CoreAPI
      run: dotnet build --no-restore OnlineShopAPI/OnlineShopAPI/OnlineShopAPI.csproj
    - name: Build IdentityServer
      run: dotnet build --no-restore OnlineShopAPI/IdentityServer/IdentityServer.csproj
    
